updates for all types of processing software

diff --git a/meteosat/run/bufrmeto b/meteosat/run/bufrmeto
--- a/meteosat/run/bufrmeto
+++ b/meteosat/run/bufrmeto
@@ -6,9 +6,13 @@ tabl=$root/fix/satwnd.tab
 module load netcdf/4.7.4
 
 yrmn=$1; yrm1=$(bumpidx $yrmn -1)
-data=$2; prnt=${3:-prnt}
+year=$(echo $yrmn|cut -c 1-4)
+data=$ptmp/satwnd.$year/meto
+arch=$ptmp/satwnd.$year
+prnt=${3:-prnt}
 
 # setup individual data files for the month in dird
+# -------------------------------------------------
 
 dird=$data/dird.$yrmn
 rm -rf    $dird
@@ -17,11 +21,14 @@ cd        $dird
 
 for yymm in $yrm1 $yrmn; do 
 for file in $(ls $data/M*$yymm*tgz); do
+set +e
 [[ $yymm = $yrm1 ]] && tar --wildcards -zxf $file \*$(bumpidx ${yrmn}01 -1)\*
+set -e
 [[ $yymm = $yrmn ]] && tar --wildcards -zxf $file
 done;done
 
-# translate the netcdf into bufr in dest
+# translate the netcdf into bufr into dest
+# ----------------------------------------
 
 dest=$data/dest.$yrmn
 rm -rf    $dest
@@ -39,5 +46,12 @@ $prnt
 eof
 done
 
-rm -rf $dird
+# tar up each satellite month in dest - cleanup leftovers
+# -------------------------------------------------------
+
+for sat in $(ls satwnd*$yrmn*|uniq -w13|cut -d'.' -f1-2); do
+tar -cf $arch/$sat.$yrmn $sat.$yrmn????
+done
+
+cd $arch; rm -rf $dird $dest
 
diff --git a/ssmi/run/runtsh b/ssmi/run/runtsh
--- a/ssmi/run/runtsh
+++ b/ssmi/run/runtsh
@@ -1,23 +1,31 @@
 set -euax
 
+yrmn=$1
+subd=$PWD
 root=$(cd ..;pwd)
-yrmn=$1; yrml=$(bumpidx $yrmn -1)
-data=$ptmp/ssmidata; mkdir -p $data
+yrml=$(bumpidx $yrmn -1)
+year=$(echo $yrmn|cut -c 1-4)
+data=$ptmp/ssmidata.$year; mkdir -p $data
 runt=$yrmn; source $root/build/build.wc2
 
 dest=$data/dest.$yrmn; rm -rf $dest; mkdir $dest; cd $dest 
 ln -sf $root/fix/ssmit.tab fort.50
+
+# extract the raw data and convert each satellite for this month
+# --------------------------------------------------------------
 
 for mnth in $yrml $yrmn; do
 for file in $(ls $data/SSMI*$mnth); do
 
 dird=$data/dird.$yrmn; rm -rf $dird; mkdir $dird; cd $dird 
 
+set +e
 if [[ $(echo $file|cut -d- -f5) = $yrml ]]; then
  tar --wildcards -xvf $file  \*$(bumpidx ${yrmn}01 -1)\*
 else
  tar -xvf $file 
 fi
+set -e
 
 cd $dest
 
@@ -29,4 +37,21 @@ done
 done
 done
 
-rm -rf $data/dird.$yrmn
+rm -rf $data/dird.$yrmn 
+rm -f  fort.*
+
+# tar up each satellite month in dest - cleanup leftovers
+# -------------------------------------------------------
+
+for sat in $(ls SSMI*$yrmn*|uniq -w13|cut -d'.' -f1-2); do
+tar -cf $sat.$yrmn $sat.$yrmn????
+rm -f $sat.??????????
+done; ls -lh
+
+# combine the satellites for the month and copy the full files to aws
+# -------------------------------------------------------------------
+
+$subd/putssmi $yrmn
+
+
+
diff --git a/ssmis/run/runts b/ssmis/run/runts
--- a/ssmis/run/runts
+++ b/ssmis/run/runts
@@ -1,32 +1,70 @@
 #!/usr/bin/env bash
 set -eua
 
-cd $(dirname $0); root=$(cd ..;pwd); compile wc2 
+cd $(dirname $0); root=$(cd ..;pwd)
+module load netcdf/4.7.4
+set -x
+
+
+# parameters for this month
+# -------------------------
 
 yrmn=$1
-data=$2; mkdir -p $data
-dest=$data/dest; rm -rf $dest; mkdir -p $dest
+year=$(echo $yrmn|cut -c 1-4)
+data=$ptmp/ssmisdata.$year
+
+here=$data/here; mkdir -p $here; cd $here
+dird=$here/dird.$yrmn; rm -rf $dird
+mkdir $dird; cd $dird
+
+# parameters for last month
+# -------------------------
 
 yrml=$(bumpidx ${yrmn}    -1)
 ymdl=$(bumpidx ${yrmn}01  -1)
+yeal=$(echo $yrml|cut -c 1-4)
+datl=$ptmp/ssmisdata.$yeal
 
-# stage the data for the month
+# stage the data for last month
+# -----------------------------
 
-cd $data; rm -f BTRin*
-
-for file in SSMIS*$yrml; do
+for file in $datl/SSMIS*$yrml; do
+set +e
 tar --wildcards -xvf $file BTRin$ymdl\*  
+set -e
 done
-for file in SSMIS*$yrmn; do
+
+# stage the data for this month
+# -----------------------------
+
+for file in $data/SSMIS*$yrmn; do
 tar -xvf $file 
 done
 
 # convert the data for the month
+# ------------------------------
 
-cd $dest; cp $root/fix/b021.tab $dest
+mkdir dest; cd dest
+cp $root/fix/b021.tab .
 
-for file in $(ls $data/BTRin*); do
+for file in $(ls $dird/BTRin*); do
 echo $(date) $file
 echo $file | $root/exec/exec_smis_2_gsi
 done
 
+# tarup any of the satellites that were converted
+# -----------------------------------------------
+
+for sat in $(ls SSMIS*$yrmn*|uniq -w13|cut -d'.' -f1-2); do
+echo $(date) tarring $sat; tar -cf $here/$sat.$yrmn $sat.$yrmn????
+done
+
+# combine into DA synoptic files and move to aws
+# ----------------------------------------------
+
+$subd/putawsd $yrmn
+
+# cleanup working space and exit
+# ------------------------------
+
+cd $here; rm -rf $dird
